---
require:
  - rubocop-rake
  - rubocop-sorbet
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  Exclude:
    - "**/node_modules/**/*"
    - "**/pkg/**"
    - "**/target/**/*"
    - "**/vendor/**/*"
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Enabled: true
  Exclude:
    - "**/Rakefile"
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics:
  Enabled: false
Sorbet/EnforceSignatures:
  Enabled: true
Sorbet/ForbidTUntyped:
  Enabled: true
Sorbet/HasSigil:
  Enabled: true
  SuggestedStrictness: strict
  MinimumStrictness: strict
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/Documentation:
  Enabled: false
