---
require:
  - rubocop-rake
  - rubocop-sorbet
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  Exclude:
    - "**/node_modules/**/*"
    - "**/target/**/*"
    - "**/vendor/**/*"
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Enabled: true
  Exclude:
    - "**/Rakefile"
    - "**/extn/**/*"
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false # See GH-679.
