---
name: "Generate THIRDPARTY"
description: "Generate license listing of third party dependencies in Artichoke Ruby"

inputs:
  artichoke_ref:
    required: true
    type: string
  target_triple:
    required: true
    type: string
  output_file:
    required: true
    type: string
  github_token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Clone Artichoke
      uses: actions/checkout@v3
      with:
        repository: artichoke/artichoke
        ref: ${{ inputs.artichoke_ref }}
        path: "generate-third-party-artichoke-${{ inputs.artichoke_ref }}"

    - name: Install Ruby toolchain
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_WITHOUT: development
      with:
        ruby-version: "3.1.2"
        bundler-cache: true
        working-directory: ${{ github.action_path }}

    - name: Install cargo-about
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bundle exec install-cargo-about "${{ runner.os }}"
      env:
        BUNDLE_WITHOUT: development
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Generate THIRDPARTY
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        bundle exec generate-third-party-text-file-single-target \
          "${{ inputs.target_triple }}" \
          "${{ github.workspace }}/generate-third-party-artichoke-${{ inputs.artichoke_ref }}/Cargo.toml" \
          > "${{ inputs.output_file }}"
      env:
        BUNDLE_WITHOUT: development

    - name: Cleanup
      shell: bash
      run: rm -rf "${{ github.workspace }}/generate-third-party-artichoke-${{ inputs.artichoke_ref }}"
