---
name: "Generate THIRDPARTY"
description: "Generate license listing of third party dependencies in Artichoke Ruby"

inputs:
  artichoke_ref:
    required: true
    type: string
  target_triple:
    required: true
    type: string
  output_file:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Clone Artichoke
      uses: actions/checkout@v3
      with:
        repository: artichoke/artichoke
        ref: ${{ inputs.artichoke_ref }}
        path: "artichoke-${{ inputs.artichoke_ref }}"

    - name: Install Ruby toolchain
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_WITHOUT: development
      with:
        ruby-version: "3.1.2"
        bundler-cache: true
        working-directory: ${{ github.action_path }}

    - name: Install cargo-about for Linux
      shell: bash
      if: runner.os == 'Linux'
      run: |
        release_info="$(curl \
          --silent \
          --show-error \
          --retry 5 \
          --fail \
          --header "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/EmbarkStudios/cargo-about/releases"
        )"
        release_url="$(echo "$release_info" | jq -r '
          .[0].assets
          | map(select(.browser_download_url
          | test(".*x86_64-unknown-linux.*tar.gz$")))
          | .[0].browser_download_url
          '
        )"
        curl --silent --show-error --retry 5 --fail --location "$release_url" | tar xvz -C /usr/local/bin/ --strip-components=1

    - name: Install cargo-about for macOS
      shell: bash
      if: runner.os == 'macOS'
      run: |
        release_info="$(curl \
          --silent \
          --show-error \
          --retry 5 \
          --fail \
          --header "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/EmbarkStudios/cargo-about/releases"
        )"
        release_url="$(echo "$release_info" | jq -r '
          .[0].assets
          | map(select(.browser_download_url
          | test(".*x86_64-apple-darwin.*tar.gz$")))
          | .[0].browser_download_url
          '
        )"
        curl --silent --show-error --retry 5 --fail --location "$release_url" | gtar xvz -C /usr/local/bin/ --strip-components=1

    - name: Install cargo-about for Windows
      shell: bash
      if: runner.os == 'Windows'
      run: |
        release_info="$(curl \
          --silent \
          --show-error \
          --retry 5 \
          --fail \
          --header "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/EmbarkStudios/cargo-about/releases"
        )"
        release_url="$(echo "$release_info" | jq -r '
          .[0].assets
          | map(select(.browser_download_url
          | test(".*x86_64-pc-windows-msvc.*tar.gz$")))
          | .[0].browser_download_url
          '
        )"
        mkdir '${{ github.workspace }}\cargo-about-bin'
        curl --silent --show-error --retry 5 --fail --location "$release_url" > '${{ github.workspace }}\cargo-about-bin\cargo-about.tar.gz'
        cd '${{ github.workspace }}\cargo-about-bin'
        tar xvzf 'cargo-about.tar.gz' -C '.' --strip-components=1
        echo '${{ github.workspace }}\cargo-about-bin' >> $GITHUB_PATH

    - name: Generate THIRDPARTY
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        bundle exec generate-third-party-text-file-single-target \
          "${{ inputs.target_triple }}" \
          "${{ github.workspace }}/artichoke-${{ inputs.artichoke_ref }}/Cargo.toml" \
          > "${{ inputs.output_file }}"
      env:
        BUNDLE_WITHOUT: development
